"""Locally execute the bounded change-to-content-consumer candidate loop.

This is deliberately *not* a watcher, model dispatcher, publisher, or a claim
that two humans/agents made a semantic judgment.  Given sealed local inputs it
performs a deterministic producer-and-review simulation and writes typed
evidence records in a caller-chosen empty directory.  It makes the previously
planned route auditable end-to-end while preserving the public boundary.
"""

from __future__ import annotations

import hashlib
import json
from pathlib import Path
from typing import Any, Mapping

from .channel_package import verify_channel_package_files
from .content_impact_review_plan import verify_content_impact_review_plan
from .content_roles import CONTENT_PRODUCER_ARTIFACT_TYPES, CONTENT_PRODUCER_OUTPUTS, CONTRACT_ID, validate_content_role_output
from .content_update_receipt import verify_content_update_receipt
from .integrity import canonical_hash, verify_self_hash
from .registry import ValidationError, atomic_create_json
from .resources import SCHEMAS_ROOT
from .schema_validation import load_validated_json, validate_payload


PACKAGE_REGISTRY_SCHEMA = SCHEMAS_ROOT / "content-package-instance-registry.schema.json"
RUN_SCHEMA = SCHEMAS_ROOT / "content-consumer-machine-run.schema.json"
REWORK_SCHEMA = SCHEMAS_ROOT / "content-consumer-local-rework.schema.json"
CORRECTION_SCHEMA = SCHEMAS_ROOT / "content-consumer-local-correction.schema.json"
PACKAGE_BOUNDARY = (
    "private package-instance inventory only; it proves local immutable bindings and planned withdrawal/rebuild routing, never publication, dispatch, authorization, or external reach."
)
RUN_BOUNDARY = (
    "local deterministic candidate execution only; records are generated by this bounded harness, not live agents or human semantic review. No source mutation, model call, network, credential use, scheduling, publication, withdrawal, or external send occurred or is authorized."
)
REWORK_BOUNDARY = (
    "local deterministic corrective-binding record only; it binds a failed local run to a distinct successor graph and package registry, and does not itself mutate source material, call a model, dispatch an agent, publish, withdraw, schedule, use credentials, access a network, or send externally."
)
CORRECTION_BOUNDARY = (
    "local deterministic corrective-target record only; it binds one failed local work item to the same target in a successor local receipt and does not itself mutate source material, call a model, dispatch an agent, publish, withdraw, schedule, use credentials, access a network, or send externally."
)
INDEPENDENCE_SCOPE = "separate deterministic evaluator identity and separately sealed result; not a human or model-independence claim"
EFFECTS = {
    "producer_execution": "local_deterministic_candidate_completed", "model_call": "not_attempted",
    "source_material": "not_mutated", "publish": "not_attempted", "withdrawal": "not_attempted",
    "network": "not_attempted", "credential_use": "not_attempted", "external_send": "not_attempted",
    "schedule": "not_attempted",
}


def _hash(path: Path) -> str:
    return "sha256:" + hashlib.sha256(path.read_bytes()).hexdigest()


def _root(value: Path | str) -> Path:
    root = Path(value).resolve(strict=True)
    if root.is_symlink() or not root.is_dir():
        raise ValidationError("CONTENT-CONSUMER-MACHINE-ROOT-UNSAFE")
    return root


def _file(root: Path, value: Path | str, error: str) -> tuple[Path, str]:
    candidate = Path(value)
    candidate = candidate if candidate.is_absolute() else root / candidate
    try:
        resolved = candidate.resolve(strict=True)
        relative = resolved.relative_to(root)
    except (OSError, ValueError) as exc:
        raise ValidationError(error) from exc
    if resolved.is_symlink() or not resolved.is_file() or any((root / Path(*relative.parts[:i])).is_symlink() for i in range(1, len(relative.parts) + 1)):
        raise ValidationError(error)
    return resolved, relative.as_posix()


def _directory(root: Path, value: Path | str, error: str) -> tuple[Path, str]:
    candidate = Path(value)
    candidate = candidate if candidate.is_absolute() else root / candidate
    try:
        resolved = candidate.resolve(strict=True)
        relative = resolved.relative_to(root)
    except (OSError, ValueError) as exc:
        raise ValidationError(error) from exc
    if resolved.is_symlink() or not resolved.is_dir():
        raise ValidationError(error)
    return resolved, relative.as_posix()


def _registry_id(unsigned: dict[str, Any]) -> str:
    return "content-package-registry-" + canonical_hash({**unsigned, "registry_id": ""}).removeprefix("sha256:")[:24]


def _run_id(unsigned: dict[str, Any]) -> str:
    return "content-consumer-run-" + canonical_hash({**unsigned, "run_id": ""}).removeprefix("sha256:")[:24]


def _all_asset_ids(package: Mapping[str, Any]) -> list[str]:
    ids = {item["asset_id"] for item in package["assets"]}
    for track in package.get("audience_tracks", []):
        ids.update(track["entry_asset_ids"])
    return sorted(ids)


def build_package_instance_registry(*, graph_root: Path | str, package_directory: Path | str) -> dict[str, Any]:
    """Inventory every JSON package in a declared directory, fail closed on any one invalid file."""

    root = _root(graph_root)
    directory, directory_ref = _directory(root, package_directory, "CONTENT-PACKAGE-REGISTRY-DIRECTORY-UNSAFE")
    # The package export scope is deliberately flat.  Do not silently skip a
    # symlink, nested package, or a non-JSON sibling: any of those would make
    # a registry appear complete while leaving a package-shaped object outside
    # the immutable inventory.
    paths: list[Path] = []
    for path in sorted(directory.iterdir(), key=lambda item: item.name):
        if path.is_symlink():
            raise ValidationError("CONTENT-PACKAGE-REGISTRY-SYMLINK-ENTRY-FORBIDDEN")
        if path.is_dir():
            raise ValidationError("CONTENT-PACKAGE-REGISTRY-NESTED-ENTRY-FORBIDDEN")
        if not path.is_file():
            raise ValidationError("CONTENT-PACKAGE-REGISTRY-UNSUPPORTED-ENTRY-FORBIDDEN")
        if path.suffix != ".json":
            raise ValidationError("CONTENT-PACKAGE-REGISTRY-NONJSON-ENTRY-FORBIDDEN")
        paths.append(path)
    if not paths:
        raise ValidationError("CONTENT-PACKAGE-REGISTRY-EMPTY-SCOPE")
    instances: list[dict[str, Any]] = []
    graph_identity: dict[str, str] | None = None
    seen_ids: set[str] = set()
    for path in paths:
        path_ref = path.relative_to(root).as_posix()
        result = verify_channel_package_files(path, root=root)
        package = json.loads(path.read_text(encoding="utf-8"))
        if result["authorized"]:
            raise ValidationError("CONTENT-PACKAGE-REGISTRY-AUTHORIZED-PACKAGE-FORBIDDEN")
        source = package["source_graph"]
        identity = {key: source[key] for key in ("graph_id", "content_hash", "candidate_id", "snapshot_id", "version_id")}
        identity["graph_hash"] = identity.pop("content_hash")
        if graph_identity is None:
            graph_identity = identity
        elif graph_identity != identity:
            raise ValidationError("CONTENT-PACKAGE-REGISTRY-GRAPH-MISMATCH")
        if package["package_id"] in seen_ids:
            raise ValidationError("CONTENT-PACKAGE-REGISTRY-DUPLICATE-PACKAGE-ID")
        seen_ids.add(package["package_id"])
        graph_path, _ = _file(root, package["source_graph"]["source_path"], "CONTENT-PACKAGE-REGISTRY-GRAPH-PATH-UNSAFE")
        try:
            graph = json.loads(graph_path.read_text(encoding="utf-8"))
            relations = {item["asset_id"]: item for item in graph["asset_relations"]}
        except (OSError, json.JSONDecodeError, KeyError, TypeError) as exc:
            raise ValidationError("CONTENT-PACKAGE-REGISTRY-GRAPH-INVALID") from exc
        asset_ids = _all_asset_ids(package)
        try:
            dependency_channels = {package["channel"]["channel_id"]}
            for asset_id in asset_ids:
                dependency_channels.update(relations[asset_id]["channel_ids"])
        except (KeyError, TypeError) as exc:
            raise ValidationError("CONTENT-PACKAGE-REGISTRY-DEPENDENCY-INVALID") from exc
        instances.append({
            "instance_id": package["package_id"], "package_path": path_ref,
            "package_id": package["package_id"], "package_hash": package["package_hash"],
            "channel_id": package["channel"]["channel_id"], "locale": package["channel"]["locale"],
            "asset_ids": asset_ids, "dependency_channel_ids": sorted(dependency_channels),
            "limitation_ids": package["limitation_ids"],
        })
    assert graph_identity is not None
    unsigned = {
        "schema_version": "content-package-instance-registry/v1", "registry_id": "",
        "scope": {"package_directory": directory_ref, "package_paths": [path.relative_to(root).as_posix() for path in paths]},
        "source_graph": graph_identity, "instances": sorted(instances, key=lambda item: item["instance_id"]),
        "boundary": PACKAGE_BOUNDARY,
    }
    unsigned["registry_id"] = _registry_id(unsigned)
    registry = {**unsigned, "registry_hash": canonical_hash(unsigned)}
    validate_payload(registry, PACKAGE_REGISTRY_SCHEMA, "content package instance registry")
    return registry


def create_package_instance_registry(*, graph_root: Path | str, package_directory: Path | str, output: Path | str) -> dict[str, Any]:
    registry = build_package_instance_registry(graph_root=graph_root, package_directory=package_directory)
    target = Path(output)
    if target.is_symlink():
        raise ValidationError("CONTENT-PACKAGE-REGISTRY-PATH-UNSAFE")
    atomic_create_json(target, registry)
    return registry


def verify_package_instance_registry(path: Path | str, *, graph_root: Path | str) -> dict[str, Any]:
    root = _root(graph_root)
    target, _ = _file(root, path, "CONTENT-PACKAGE-REGISTRY-PATH-UNSAFE")
    registry = load_validated_json(target, PACKAGE_REGISTRY_SCHEMA, "content package instance registry")
    verify_self_hash(registry, "registry_hash")
    unsigned = {key: value for key, value in registry.items() if key != "registry_hash"}
    if registry["registry_id"] != _registry_id(unsigned) or registry["boundary"] != PACKAGE_BOUNDARY:
        raise ValidationError("CONTENT-PACKAGE-REGISTRY-IDENTITY-INVALID")
    rebuilt = build_package_instance_registry(graph_root=root, package_directory=registry["scope"]["package_directory"])
    if rebuilt != registry:
        raise ValidationError("CONTENT-PACKAGE-REGISTRY-RECOMPUTATION-MISMATCH")
    return registry


def _identity(path_ref: str, record: Mapping[str, Any], *, key: str) -> dict[str, str]:
    return {"source_path": path_ref, "identity": record[key], "content_hash": record["plan_hash"] if key == "plan_id" else record["receipt_hash"] if key == "receipt_id" else record["registry_hash"]}


def _expected_graph(plan: Mapping[str, Any]) -> dict[str, str]:
    current = plan["current"]
    return {"graph_id": current["graph_id"], "graph_hash": current["graph_hash"], "candidate_id": current["candidate_id"], "snapshot_id": current["snapshot_id"], "version_id": current["version_id"], "verification": "verified_content_graph_v3"}


def _expected_plan(plan: Mapping[str, Any]) -> dict[str, str]:
    return {"plan_id": plan["plan_id"], "plan_hash": plan["plan_hash"], "verification": "verified_content_impact_review_plan"}


def _producer_payload(role_id: str, work_item: Mapping[str, Any], plan: Mapping[str, Any]) -> dict[str, Any]:
    artifact_type = sorted(CONTENT_PRODUCER_ARTIFACT_TYPES[role_id])[0]
    return {
        "schema_version": "content-role-output/v1", "role_id": role_id, "contract_id": CONTRACT_ID,
        "output_kind": CONTENT_PRODUCER_OUTPUTS[role_id], "source_graph": _expected_graph(plan),
        "impact_review_plan": _expected_plan(plan),
        "drafts": [{"draft_id": f"{work_item['work_item_id']}:{role_id}", "artifact_type": artifact_type,
                    "content": f"Deterministic private candidate output for {work_item['kind']}:{work_item['target_id']}.",
                    "claim_ids": [], "limitation_ids": ["limitation.local-deterministic-candidate"], "state": "draft_or_review_only"}],
        "mutation_attestation": {"claim_registry": "not_mutated", "evidence_registry": "not_mutated", "candidate_state": "not_mutated", "approval_state": "not_mutated", "analytics_source_data": "not_mutated"},
        "effect_attestation": {"publish": "not_attempted", "network": "not_attempted", "credential_use": "not_attempted", "external_send": "not_attempted", "schedule": "not_attempted"},
        "boundary": "private typed draft/review output only; no Content Graph mutation, claim promotion, approval, publication, network action, credential use, scheduling, or external send.",
    }


def _review_payload(*, work_item: Mapping[str, Any], reviewer_role_id: str, producer_hashes: list[str], verdict: str) -> dict[str, Any]:
    unsigned = {"schema_version": "content-consumer-local-review/v1", "work_item_id": work_item["work_item_id"], "reviewer_role_id": reviewer_role_id, "producer_record_hashes": producer_hashes, "verdict": verdict, "execution_mode": "local_deterministic_candidate", "independence_scope": INDEPENDENCE_SCOPE, "effect_attestation": {"network": "not_attempted", "external_send": "not_attempted", "publish": "not_attempted"}}
    return {**unsigned, "review_hash": canonical_hash(unsigned)}


def _validate_review(payload: Mapping[str, Any], *, work_item: Mapping[str, Any], reviewer_role_id: str, producer_hashes: list[str]) -> None:
    keys = {"schema_version", "work_item_id", "reviewer_role_id", "producer_record_hashes", "verdict", "execution_mode", "independence_scope", "effect_attestation", "review_hash"}
    if set(payload) != keys or payload["schema_version"] != "content-consumer-local-review/v1" or payload["work_item_id"] != work_item["work_item_id"] or payload["reviewer_role_id"] != reviewer_role_id or payload["producer_record_hashes"] != producer_hashes or payload["verdict"] not in {"pass", "fail"} or payload["execution_mode"] != "local_deterministic_candidate" or payload["independence_scope"] != INDEPENDENCE_SCOPE or payload["effect_attestation"] != {"network": "not_attempted", "external_send": "not_attempted", "publish": "not_attempted"}:
        raise ValidationError("CONTENT-CONSUMER-MACHINE-REVIEW-INVALID")
    verify_self_hash(dict(payload), "review_hash")


def _outcome(outcomes: Mapping[str, Mapping[str, str]] | None, work_id: str, reviewer: str) -> str:
    verdict = (outcomes or {}).get(work_id, {}).get(reviewer, "pass")
    if verdict not in {"pass", "fail"}:
        raise ValidationError("CONTENT-CONSUMER-MACHINE-REVIEW-OUTCOME-INVALID")
    return verdict


def _package_actions(registry: Mapping[str, Any], plan: Mapping[str, Any], receipt: Mapping[str, Any], closure: Mapping[str, str]) -> list[dict[str, Any]]:
    review_assets = set(plan["ripple"]["review_asset_ids"])
    invalidated_channels = set(plan["ripple"]["invalidated_channel_package_ids"])
    result: list[dict[str, Any]] = []
    for instance in registry["instances"]:
        affected = sorted(set(instance["asset_ids"]) & review_assets)
        affected_channels = sorted(set(instance["dependency_channel_ids"]) & invalidated_channels)
        if not affected and not affected_channels:
            result.append({"instance_id": instance["instance_id"], "package_hash": instance["package_hash"], "affected_asset_ids": [], "affected_channel_ids": [], "related_work_item_ids": [], "withdrawal_plan": "no withdrawal is required because this immutable package instance is outside the computed impact set", "rebuild_plan": "retain the current immutable package instance; no rebuild is required for this computed impact set", "state": "not_affected_current_instance"})
            continue
        related = [item["work_item_id"] for item in receipt["staged_update_plan"] if (item["kind"] == "review_asset" and item["target_id"] in affected) or (item["kind"] == "reassemble_channel_package" and item["target_id"] in affected_channels)]
        if not related:
            raise ValidationError("CONTENT-CONSUMER-MACHINE-PACKAGE-ROUTING-INCOMPLETE")
        state = "rebuild_and_withdrawal_plan_ready" if all(closure[item] == "closed_local_candidate" for item in related) else "rebuild_blocked_unresolved_review"
        result.append({"instance_id": instance["instance_id"], "package_hash": instance["package_hash"], "affected_asset_ids": affected, "affected_channel_ids": affected_channels, "related_work_item_ids": sorted(related), "withdrawal_plan": "mark this private candidate package invalid for any external use; no withdrawal action is executed", "rebuild_plan": "rebuild only from the current verified graph, then revalidate package bytes and obtain a new local candidate closure", "state": state})
    return sorted(result, key=lambda item: item["instance_id"])


def _rework_id(unsigned: Mapping[str, Any]) -> str:
    return "content-consumer-rework-" + canonical_hash({**unsigned, "rework_id": ""}).removeprefix("sha256:")[:24]


def _failed_work_item_ids(run: Mapping[str, Any]) -> list[str]:
    return sorted(item["work_item_id"] for item in run["work_closure"] if item["state"] == "blocked_review_failure")


def _successor_identity(plan: Mapping[str, Any], registry: Mapping[str, Any], receipt: Mapping[str, Any]) -> dict[str, Any]:
    return {
        "source_graph": _expected_graph(plan),
        "package_registry": {"registry_id": registry["registry_id"], "registry_hash": registry["registry_hash"]},
        "update_receipt": {"receipt_id": receipt["receipt_id"], "receipt_hash": receipt["receipt_hash"]},
    }


def _correction_id(unsigned: Mapping[str, Any]) -> str:
    return "content-consumer-correction-" + canonical_hash({**unsigned, "correction_id": ""}).removeprefix("sha256:")[:24]


def _work_by_id(receipt: Mapping[str, Any], work_item_id: str) -> dict[str, Any]:
    matches = [item for item in receipt["staged_update_plan"] if item["work_item_id"] == work_item_id]
    if len(matches) != 1:
        raise ValidationError("CONTENT-CONSUMER-MACHINE-CORRECTION-WORK-INVALID")
    return matches[0]


def _same_corrective_target(failed_item: Mapping[str, Any], successor_item: Mapping[str, Any]) -> bool:
    return (
        failed_item["kind"] == successor_item["kind"]
        and failed_item["target_id"] == successor_item["target_id"]
    )


def create_local_content_correction_artifact(
    *, graph_root: Path | str, failed_run_path: Path | str, successor_update_receipt_path: Path | str,
    failed_work_item_id: str, output: Path | str,
) -> dict[str, Any]:
    """Seal one bounded failed-work-to-successor-target corrective record."""

    root = _root(graph_root)
    failed_path, failed_ref = _file(root, failed_run_path, "CONTENT-CONSUMER-MACHINE-CORRECTION-FAILED-RUN-PATH-UNSAFE")
    receipt_path, receipt_ref = _file(root, successor_update_receipt_path, "CONTENT-CONSUMER-MACHINE-CORRECTION-RECEIPT-PATH-UNSAFE")
    failed = verify_local_content_consumer_machine_run(failed_path, graph_root=root)
    if failed_work_item_id not in _failed_work_item_ids(failed):
        raise ValidationError("CONTENT-CONSUMER-MACHINE-CORRECTION-REQUIRES-BLOCKED-WORK")
    failed_receipt = verify_content_update_receipt(root / failed["inputs"]["update_receipt"]["source_path"], graph_root=root)
    failed_item = _work_by_id(failed_receipt, failed_work_item_id)
    successor_receipt = verify_content_update_receipt(receipt_path, graph_root=root)
    matching = [item for item in successor_receipt["staged_update_plan"] if _same_corrective_target(failed_item, item)]
    if len(matching) != 1:
        raise ValidationError("CONTENT-CONSUMER-MACHINE-CORRECTION-SUCCESSOR-TARGET-MISSING")
    successor_item = matching[0]
    unsigned = {
        "schema_version": "content-consumer-local-correction/v1", "correction_id": "",
        "failed_run": {"source_path": failed_ref, "run_id": failed["run_id"], "run_hash": failed["run_hash"]},
        "failed_work_item": {"work_item_id": failed_item["work_item_id"], "kind": failed_item["kind"], "target_id": failed_item["target_id"]},
        "successor_receipt": {"source_path": receipt_ref, "receipt_id": successor_receipt["receipt_id"], "receipt_hash": successor_receipt["receipt_hash"]},
        "successor_work_item": {"work_item_id": successor_item["work_item_id"], "kind": successor_item["kind"], "target_id": successor_item["target_id"]},
        "correction_action": "local_candidate_corrective_target_rebound", "boundary": CORRECTION_BOUNDARY,
    }
    unsigned["correction_id"] = _correction_id(unsigned)
    artifact = {**unsigned, "correction_hash": canonical_hash(unsigned)}
    validate_payload(artifact, CORRECTION_SCHEMA, "content consumer local correction")
    target = Path(output)
    if not target.is_absolute():
        target = root / target
    if target.is_symlink():
        raise ValidationError("CONTENT-CONSUMER-MACHINE-CORRECTION-PATH-UNSAFE")
    atomic_create_json(target, artifact)
    return artifact


def verify_local_content_correction_artifact(path: Path | str, *, graph_root: Path | str) -> dict[str, Any]:
    root = _root(graph_root)
    target, _ = _file(root, path, "CONTENT-CONSUMER-MACHINE-CORRECTION-PATH-UNSAFE")
    artifact = load_validated_json(target, CORRECTION_SCHEMA, "content consumer local correction")
    verify_self_hash(artifact, "correction_hash")
    unsigned = {key: value for key, value in artifact.items() if key != "correction_hash"}
    if artifact["correction_id"] != _correction_id(unsigned) or artifact["boundary"] != CORRECTION_BOUNDARY:
        raise ValidationError("CONTENT-CONSUMER-MACHINE-CORRECTION-IDENTITY-INVALID")
    failed_path, failed_ref = _file(root, artifact["failed_run"]["source_path"], "CONTENT-CONSUMER-MACHINE-CORRECTION-FAILED-RUN-PATH-UNSAFE")
    failed = verify_local_content_consumer_machine_run(failed_path, graph_root=root)
    if artifact["failed_run"] != {"source_path": failed_ref, "run_id": failed["run_id"], "run_hash": failed["run_hash"]} or artifact["failed_work_item"]["work_item_id"] not in _failed_work_item_ids(failed):
        raise ValidationError("CONTENT-CONSUMER-MACHINE-CORRECTION-FAILED-RUN-INVALID")
    failed_receipt = verify_content_update_receipt(root / failed["inputs"]["update_receipt"]["source_path"], graph_root=root)
    failed_item = _work_by_id(failed_receipt, artifact["failed_work_item"]["work_item_id"])
    expected_failed = {key: failed_item[key] for key in ("work_item_id", "kind", "target_id")}
    if artifact["failed_work_item"] != expected_failed:
        raise ValidationError("CONTENT-CONSUMER-MACHINE-CORRECTION-FAILED-WORK-MISMATCH")
    receipt_path, receipt_ref = _file(root, artifact["successor_receipt"]["source_path"], "CONTENT-CONSUMER-MACHINE-CORRECTION-RECEIPT-PATH-UNSAFE")
    successor_receipt = verify_content_update_receipt(receipt_path, graph_root=root)
    expected_receipt = {"source_path": receipt_ref, "receipt_id": successor_receipt["receipt_id"], "receipt_hash": successor_receipt["receipt_hash"]}
    successor_item = _work_by_id(successor_receipt, artifact["successor_work_item"]["work_item_id"])
    expected_successor = {key: successor_item[key] for key in ("work_item_id", "kind", "target_id")}
    if artifact["successor_receipt"] != expected_receipt or artifact["successor_work_item"] != expected_successor or not _same_corrective_target(failed_item, successor_item):
        raise ValidationError("CONTENT-CONSUMER-MACHINE-CORRECTION-SUCCESSOR-MISMATCH")
    return artifact


def _verify_local_content_rework_payload(
    artifact: Mapping[str, Any], *, root: Path, expected_plan: Mapping[str, Any] | None = None,
    expected_registry: Mapping[str, Any] | None = None, expected_receipt: Mapping[str, Any] | None = None,
) -> dict[str, Any]:
    validate_payload(dict(artifact), REWORK_SCHEMA, "content consumer local rework")
    verify_self_hash(dict(artifact), "rework_hash")
    unsigned = {key: value for key, value in artifact.items() if key != "rework_hash"}
    if artifact["rework_id"] != _rework_id(unsigned) or artifact["boundary"] != REWORK_BOUNDARY:
        raise ValidationError("CONTENT-CONSUMER-MACHINE-REWORK-IDENTITY-INVALID")
    failed_path, failed_ref = _file(root, artifact["failed_run"]["source_path"], "CONTENT-CONSUMER-MACHINE-REWORK-FAILED-RUN-PATH-UNSAFE")
    failed = verify_local_content_consumer_machine_run(failed_path, graph_root=root)
    failed_ref_expected = {
        "source_path": failed_ref, "run_id": failed["run_id"], "run_hash": failed["run_hash"],
    }
    if artifact["failed_run"] != failed_ref_expected or failed.get("retest") is not None:
        raise ValidationError("CONTENT-CONSUMER-MACHINE-REWORK-FAILED-RUN-INVALID")
    blocked = _failed_work_item_ids(failed)
    if not blocked or artifact["blocked_work_item_ids"] != blocked:
        raise ValidationError("CONTENT-CONSUMER-MACHINE-REWORK-BLOCKED-WORK-MISMATCH")
    failed_plan = verify_content_impact_review_plan(
        root / failed["inputs"]["impact_plan"]["source_path"], graph_root=root
    )
    failed_registry = verify_package_instance_registry(
        root / failed["inputs"]["package_registry"]["source_path"], graph_root=root
    )
    successor = artifact["successor"]
    if successor["predecessor_graph_hash"] != failed_plan["current"]["graph_hash"] or successor["predecessor_package_registry_hash"] != failed_registry["registry_hash"]:
        raise ValidationError("CONTENT-CONSUMER-MACHINE-REWORK-PREDECESSOR-MISMATCH")
    if successor["source_graph"]["graph_hash"] == successor["predecessor_graph_hash"] or successor["package_registry"]["registry_hash"] == successor["predecessor_package_registry_hash"]:
        raise ValidationError("CONTENT-CONSUMER-MACHINE-REWORK-NO-SUCCESSOR-FINGERPRINT")
    correction_bindings = artifact["corrective_bindings"]
    if {item["blocked_work_item_id"] for item in correction_bindings} != set(blocked) or len(correction_bindings) != len(blocked):
        raise ValidationError("CONTENT-CONSUMER-MACHINE-REWORK-CORRECTION-COVERAGE-INCOMPLETE")
    for binding in correction_bindings:
        correction_path, correction_ref = _file(root, binding["correction_artifact"]["source_path"], "CONTENT-CONSUMER-MACHINE-REWORK-CORRECTION-PATH-UNSAFE")
        correction = verify_local_content_correction_artifact(correction_path, graph_root=root)
        if correction["successor_receipt"]["receipt_hash"] != successor["update_receipt"]["receipt_hash"]:
            raise ValidationError("CONTENT-CONSUMER-MACHINE-REWORK-CORRECTION-SUCCESSOR-MISMATCH")
        expected_binding = {
            "blocked_work_item_id": correction["failed_work_item"]["work_item_id"],
            "target_kind": correction["failed_work_item"]["kind"], "target_id": correction["failed_work_item"]["target_id"],
            "successor_work_item_id": correction["successor_work_item"]["work_item_id"],
            "correction_artifact": {"source_path": correction_ref, "correction_id": correction["correction_id"], "correction_hash": correction["correction_hash"]},
        }
        if binding != expected_binding:
            raise ValidationError("CONTENT-CONSUMER-MACHINE-REWORK-CORRECTION-BINDING-MISMATCH")
    if expected_plan is not None and expected_registry is not None and expected_receipt is not None and successor != {
        **_successor_identity(expected_plan, expected_registry, expected_receipt),
        "predecessor_graph_hash": failed_plan["current"]["graph_hash"],
        "predecessor_package_registry_hash": failed_registry["registry_hash"],
    }:
        raise ValidationError("CONTENT-CONSUMER-MACHINE-REWORK-SUCCESSOR-MISMATCH")
    return dict(artifact)


def create_local_content_rework_artifact(
    *, graph_root: Path | str, failed_run_path: Path | str, successor_impact_plan_path: Path | str,
    successor_update_receipt_path: Path | str, successor_package_registry_path: Path | str,
    correction_artifact_paths: Mapping[str, Path | str], output: Path | str,
) -> dict[str, Any]:
    """Seal a local corrective binding for a failed run and a distinct successor.

    This creates evidence of *which* local rework was retested.  It neither
    writes the successor graph/package nor converts deterministic reviews into
    a semantic or external acceptance claim.
    """

    root = _root(graph_root)
    failed_path, failed_ref = _file(root, failed_run_path, "CONTENT-CONSUMER-MACHINE-REWORK-FAILED-RUN-PATH-UNSAFE")
    plan_path, _ = _file(root, successor_impact_plan_path, "CONTENT-CONSUMER-MACHINE-REWORK-PLAN-PATH-UNSAFE")
    receipt_path, _ = _file(root, successor_update_receipt_path, "CONTENT-CONSUMER-MACHINE-REWORK-RECEIPT-PATH-UNSAFE")
    registry_path, _ = _file(root, successor_package_registry_path, "CONTENT-CONSUMER-MACHINE-REWORK-REGISTRY-PATH-UNSAFE")
    failed = verify_local_content_consumer_machine_run(failed_path, graph_root=root)
    if failed.get("retest") is not None:
        raise ValidationError("CONTENT-CONSUMER-MACHINE-REWORK-FAILED-RUN-INVALID")
    blocked = _failed_work_item_ids(failed)
    if not blocked:
        raise ValidationError("CONTENT-CONSUMER-MACHINE-REWORK-REQUIRES-FAILED-RUN")
    plan = verify_content_impact_review_plan(plan_path, graph_root=root)
    receipt = verify_content_update_receipt(receipt_path, graph_root=root)
    registry = verify_package_instance_registry(registry_path, graph_root=root)
    failed_plan = verify_content_impact_review_plan(root / failed["inputs"]["impact_plan"]["source_path"], graph_root=root)
    failed_registry = verify_package_instance_registry(root / failed["inputs"]["package_registry"]["source_path"], graph_root=root)
    successor = {
        **_successor_identity(plan, registry, receipt),
        "predecessor_graph_hash": failed_plan["current"]["graph_hash"],
        "predecessor_package_registry_hash": failed_registry["registry_hash"],
    }
    if successor["source_graph"]["graph_hash"] == successor["predecessor_graph_hash"] or successor["package_registry"]["registry_hash"] == successor["predecessor_package_registry_hash"]:
        raise ValidationError("CONTENT-CONSUMER-MACHINE-REWORK-NO-SUCCESSOR-FINGERPRINT")
    if set(correction_artifact_paths) != set(blocked):
        raise ValidationError("CONTENT-CONSUMER-MACHINE-REWORK-CORRECTION-COVERAGE-INCOMPLETE")
    corrective_bindings: list[dict[str, Any]] = []
    for work_item_id in sorted(blocked):
        correction_path, correction_ref = _file(root, correction_artifact_paths[work_item_id], "CONTENT-CONSUMER-MACHINE-REWORK-CORRECTION-PATH-UNSAFE")
        correction = verify_local_content_correction_artifact(correction_path, graph_root=root)
        if correction["failed_run"]["run_hash"] != failed["run_hash"] or correction["successor_receipt"]["receipt_hash"] != receipt["receipt_hash"] or correction["failed_work_item"]["work_item_id"] != work_item_id:
            raise ValidationError("CONTENT-CONSUMER-MACHINE-REWORK-CORRECTION-BINDING-MISMATCH")
        corrective_bindings.append({
            "blocked_work_item_id": work_item_id,
            "target_kind": correction["failed_work_item"]["kind"], "target_id": correction["failed_work_item"]["target_id"],
            "successor_work_item_id": correction["successor_work_item"]["work_item_id"],
            "correction_artifact": {"source_path": correction_ref, "correction_id": correction["correction_id"], "correction_hash": correction["correction_hash"]},
        })
    unsigned = {
        "schema_version": "content-consumer-local-rework/v1", "rework_id": "",
        "failed_run": {"source_path": failed_ref, "run_id": failed["run_id"], "run_hash": failed["run_hash"]},
        "blocked_work_item_ids": blocked, "corrective_bindings": corrective_bindings,
        "repair_action": "local_candidate_graph_and_package_rebinding",
        "successor": successor, "boundary": REWORK_BOUNDARY,
    }
    unsigned["rework_id"] = _rework_id(unsigned)
    artifact = {**unsigned, "rework_hash": canonical_hash(unsigned)}
    validate_payload(artifact, REWORK_SCHEMA, "content consumer local rework")
    target = Path(output)
    if not target.is_absolute():
        target = root / target
    if target.is_symlink():
        raise ValidationError("CONTENT-CONSUMER-MACHINE-REWORK-PATH-UNSAFE")
    atomic_create_json(target, artifact)
    return artifact


def verify_local_content_rework_artifact(
    path: Path | str, *, graph_root: Path | str, expected_plan: Mapping[str, Any] | None = None,
    expected_registry: Mapping[str, Any] | None = None, expected_receipt: Mapping[str, Any] | None = None,
) -> dict[str, Any]:
    root = _root(graph_root)
    target, _ = _file(root, path, "CONTENT-CONSUMER-MACHINE-REWORK-PATH-UNSAFE")
    artifact = load_validated_json(target, REWORK_SCHEMA, "content consumer local rework")
    return _verify_local_content_rework_payload(
        artifact, root=root, expected_plan=expected_plan, expected_registry=expected_registry, expected_receipt=expected_receipt,
    )


def _retest_context(path_ref: str, artifact: Mapping[str, Any]) -> dict[str, Any]:
    return {
        "rework_artifact": {"source_path": path_ref, "rework_id": artifact["rework_id"], "rework_hash": artifact["rework_hash"]},
        "failed_run": artifact["failed_run"], "successor": artifact["successor"],
    }


def execute_local_content_consumer_machine(*, graph_root: Path | str, impact_plan_path: Path | str, update_receipt_path: Path | str, package_registry_path: Path | str, output_directory: Path | str, review_outcomes: Mapping[str, Mapping[str, str]] | None = None, rework_artifact_path: Path | str | None = None) -> dict[str, Any]:
    """Create actual local producer/reviewer records and a closure receipt. No role process is started."""
    root = _root(graph_root)
    plan_path, plan_ref = _file(root, impact_plan_path, "CONTENT-CONSUMER-MACHINE-PLAN-PATH-UNSAFE")
    receipt_path, receipt_ref = _file(root, update_receipt_path, "CONTENT-CONSUMER-MACHINE-RECEIPT-PATH-UNSAFE")
    registry_path, registry_ref = _file(root, package_registry_path, "CONTENT-CONSUMER-MACHINE-REGISTRY-PATH-UNSAFE")
    plan = verify_content_impact_review_plan(plan_path, graph_root=root)
    receipt = verify_content_update_receipt(receipt_path, graph_root=root)
    registry = verify_package_instance_registry(registry_path, graph_root=root)
    if receipt["source_review_plan"]["plan_id"] != plan["plan_id"] or receipt["source_review_plan"]["plan_hash"] != plan["plan_hash"]:
        raise ValidationError("CONTENT-CONSUMER-MACHINE-RECEIPT-PLAN-MISMATCH")
    if registry["source_graph"]["graph_hash"] != plan["current"]["graph_hash"]:
        raise ValidationError("CONTENT-CONSUMER-MACHINE-REGISTRY-GRAPH-MISMATCH")
    retest: dict[str, Any] | None = None
    if rework_artifact_path is not None:
        rework_path, rework_ref = _file(root, rework_artifact_path, "CONTENT-CONSUMER-MACHINE-REWORK-PATH-UNSAFE")
        rework = verify_local_content_rework_artifact(
            rework_path, graph_root=root, expected_plan=plan, expected_registry=registry, expected_receipt=receipt,
        )
        retest = _retest_context(rework_ref, rework)
    output = Path(output_directory)
    if not output.is_absolute():
        output = root / output
    if output.exists():
        raise ValidationError("CONTENT-CONSUMER-MACHINE-OUTPUT-ALREADY-EXISTS")
    output.mkdir(parents=True)
    output_ref = output.resolve().relative_to(root).as_posix()
    producer_records: list[dict[str, Any]] = []
    review_records: list[dict[str, Any]] = []
    closures: list[dict[str, Any]] = []
    states: dict[str, str] = {}
    for item in receipt["staged_update_plan"]:
        record_hashes: list[str] = []
        for role_id in item["assigned_role_ids"]:
            payload = _producer_payload(role_id, item, plan)
            validate_content_role_output(payload, role_id=role_id, expected_graph=_expected_graph(plan), expected_review_plan=_expected_plan(plan))
            target = output / "producer" / item["work_item_id"] / f"{role_id}.json"
            atomic_create_json(target, payload)
            record_hashes.append(_hash(target))
            producer_records.append({"work_item_id": item["work_item_id"], "role_id": role_id, "record_path": target.relative_to(root).as_posix(), "content_hash": record_hashes[-1], "verification": "verified_content_role_output"})
        review_hashes: list[str] = []
        for reviewer in item["reviewer_role_ids"]:
            payload = _review_payload(work_item=item, reviewer_role_id=reviewer, producer_hashes=record_hashes, verdict=_outcome(review_outcomes, item["work_item_id"], reviewer))
            target = output / "review" / item["work_item_id"] / f"{reviewer}.json"
            atomic_create_json(target, payload)
            review_hashes.append(_hash(target))
            review_records.append({"work_item_id": item["work_item_id"], "reviewer_role_id": reviewer, "review_instance_id": f"local-deterministic:{reviewer}", "record_path": target.relative_to(root).as_posix(), "content_hash": review_hashes[-1], "verdict": payload["verdict"], "independence_scope": INDEPENDENCE_SCOPE})
        state = "closed_local_candidate" if all(record["verdict"] == "pass" for record in review_records if record["work_item_id"] == item["work_item_id"]) else "blocked_review_failure"
        states[item["work_item_id"]] = state
        closures.append({"work_item_id": item["work_item_id"], "producer_record_hashes": record_hashes, "review_record_hashes": review_hashes, "state": state})
    package_actions = _package_actions(registry, plan, receipt, states)
    inputs = {"impact_plan": _identity(plan_ref, plan, key="plan_id"), "update_receipt": _identity(receipt_ref, receipt, key="receipt_id"), "package_registry": _identity(registry_ref, registry, key="registry_id")}
    unsigned = {"schema_version": "content-consumer-machine-run/v1", "run_id": "", "execution_mode": "local_deterministic_candidate", "authorization": "local_review_only", "inputs": inputs, "producer_records": producer_records, "review_records": review_records, "work_closure": closures, "package_actions": package_actions, "effect_attestation": EFFECTS, "boundary": RUN_BOUNDARY}
    if retest is not None:
        unsigned["retest"] = retest
    unsigned["run_id"] = _run_id(unsigned)
    run = {**unsigned, "run_hash": canonical_hash(unsigned)}
    validate_payload(run, RUN_SCHEMA, "content consumer machine run")
    atomic_create_json(output / "run.json", run)
    return run


def verify_local_content_consumer_machine_run(path: Path | str, *, graph_root: Path | str) -> dict[str, Any]:
    root = _root(graph_root)
    target, _ = _file(root, path, "CONTENT-CONSUMER-MACHINE-RUN-PATH-UNSAFE")
    run = load_validated_json(target, RUN_SCHEMA, "content consumer machine run")
    verify_self_hash(run, "run_hash")
    unsigned = {key: value for key, value in run.items() if key != "run_hash"}
    if run["run_id"] != _run_id(unsigned) or run["boundary"] != RUN_BOUNDARY or run["effect_attestation"] != EFFECTS:
        raise ValidationError("CONTENT-CONSUMER-MACHINE-RUN-IDENTITY-INVALID")
    plan = verify_content_impact_review_plan(root / run["inputs"]["impact_plan"]["source_path"], graph_root=root)
    receipt = verify_content_update_receipt(root / run["inputs"]["update_receipt"]["source_path"], graph_root=root)
    registry = verify_package_instance_registry(root / run["inputs"]["package_registry"]["source_path"], graph_root=root)
    expected = {"impact_plan": _identity(run["inputs"]["impact_plan"]["source_path"], plan, key="plan_id"), "update_receipt": _identity(run["inputs"]["update_receipt"]["source_path"], receipt, key="receipt_id"), "package_registry": _identity(run["inputs"]["package_registry"]["source_path"], registry, key="registry_id")}
    if run["inputs"] != expected:
        raise ValidationError("CONTENT-CONSUMER-MACHINE-INPUT-DRIFT")
    if "retest" in run:
        rework_ref = run["retest"].get("rework_artifact", {}).get("source_path")
        if not isinstance(rework_ref, str):
            raise ValidationError("CONTENT-CONSUMER-MACHINE-RETEST-INVALID")
        rework = verify_local_content_rework_artifact(
            rework_ref, graph_root=root, expected_plan=plan, expected_registry=registry, expected_receipt=receipt,
        )
        if run["retest"] != _retest_context(rework_ref, rework):
            raise ValidationError("CONTENT-CONSUMER-MACHINE-RETEST-DRIFT")
    work = {item["work_item_id"]: item for item in receipt["staged_update_plan"]}
    producers_by_work: dict[str, list[str]] = {}
    for record in run["producer_records"]:
        item = work.get(record["work_item_id"])
        if item is None or record["role_id"] not in item["assigned_role_ids"]:
            raise ValidationError("CONTENT-CONSUMER-MACHINE-PRODUCER-ROUTE-INVALID")
        source, _ = _file(root, record["record_path"], "CONTENT-CONSUMER-MACHINE-PRODUCER-PATH-UNSAFE")
        if _hash(source) != record["content_hash"]:
            raise ValidationError("CONTENT-CONSUMER-MACHINE-PRODUCER-HASH-MISMATCH")
        payload = json.loads(source.read_text(encoding="utf-8"))
        validate_content_role_output(payload, role_id=record["role_id"], expected_graph=_expected_graph(plan), expected_review_plan=_expected_plan(plan))
        producers_by_work.setdefault(record["work_item_id"], []).append(record["content_hash"])
    reviews_by_work: dict[str, list[dict[str, Any]]] = {}
    for record in run["review_records"]:
        item = work.get(record["work_item_id"])
        if item is None or record["reviewer_role_id"] not in item["reviewer_role_ids"] or record["independence_scope"] != INDEPENDENCE_SCOPE:
            raise ValidationError("CONTENT-CONSUMER-MACHINE-REVIEW-ROUTE-INVALID")
        source, _ = _file(root, record["record_path"], "CONTENT-CONSUMER-MACHINE-REVIEW-PATH-UNSAFE")
        if _hash(source) != record["content_hash"]:
            raise ValidationError("CONTENT-CONSUMER-MACHINE-REVIEW-HASH-MISMATCH")
        payload = json.loads(source.read_text(encoding="utf-8"))
        _validate_review(payload, work_item=item, reviewer_role_id=record["reviewer_role_id"], producer_hashes=producers_by_work.get(record["work_item_id"], []))
        if payload["verdict"] != record["verdict"]:
            raise ValidationError("CONTENT-CONSUMER-MACHINE-REVIEW-VERDICT-MISMATCH")
        reviews_by_work.setdefault(record["work_item_id"], []).append(record)
    closure_states: dict[str, str] = {}
    for closure in run["work_closure"]:
        item = work.get(closure["work_item_id"])
        records = reviews_by_work.get(closure["work_item_id"], [])
        if item is None or len(records) != 2 or {record["reviewer_role_id"] for record in records} != set(item["reviewer_role_ids"]) or closure["producer_record_hashes"] != producers_by_work.get(closure["work_item_id"], []) or closure["review_record_hashes"] != [record["content_hash"] for record in records]:
            raise ValidationError("CONTENT-CONSUMER-MACHINE-CLOSURE-INVALID")
        expected_state = "closed_local_candidate" if all(record["verdict"] == "pass" for record in records) else "blocked_review_failure"
        if closure["state"] != expected_state:
            raise ValidationError("CONTENT-CONSUMER-MACHINE-CLOSURE-STATE-INVALID")
        closure_states[closure["work_item_id"]] = closure["state"]
    if set(closure_states) != set(work):
        raise ValidationError("CONTENT-CONSUMER-MACHINE-CLOSURE-COVERAGE-INCOMPLETE")
    if run["package_actions"] != _package_actions(registry, plan, receipt, closure_states):
        raise ValidationError("CONTENT-CONSUMER-MACHINE-PACKAGE-ACTION-DRIFT")
    return run
